---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: java:openjdk-8
    commands:
      - chmod 777 gradlew
      - ./gradlew clean build
  - name: docker
    image: plugins/docker
    settings:
      username: docker_username
      password: docker_password
      repo: vinay25788/alogrithims-datastructure
      tags: latest
      dockerfile: Dockerfile